name: fastapi-app
description: FastAPI application infrastructure on AWS EC2
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
      project: fastapi-ec2

